#!/bin/bash
#
### BEGIN INIT INFO
# Provides:             socket_server.js
# Required-Start:       $syslog $remote_fs
# Required-Stop:        $syslog $remote_fs
# Should-Start:         $local_fs
# Should-Stop:          $local_fs
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    Socket chat
# Description:          Socket chat
### END INIT INFO
#
### BEGIN CHKCONFIG INFO
# chkconfig: 2345 55 25
# description: My Application
### END CHKCONFIG INFO
 
NAME="Server for socket chat"
NODE_BIN_DIR="/usr/bin"
NODE_PATH="/opt/chat/node_modules"
APPLICATION_PATH="/opt/chat/socket_server.js"
PIDFILE="/opt/chat/socket_server.pid"
LOGFILE="/opt/chat/socket_server.log"
MIN_UPTIME="5000"
SPIN_SLEEP_TIME="2000"
 
PATH=$NODE_BIN_DIR:$PATH
export NODE_PATH=$NODE_PATH
 
start() {
    echo "Starting $NAME" 
    echo "try Starting $NAME" >> $LOGFILE 

    /usr/local/bin/forever \
      --pidFile $PIDFILE \
      -a \
      -l $LOGFILE \
      --minUptime $MIN_UPTIME \
      --spinSleepTime $SPIN_SLEEP_TIME \
      start $APPLICATION_PATH 2>&1 >> $LOGFILE &
    RETVAL=$?
}
 
stop() {
    if [ -f $PIDFILE ]; then
        echo "Shutting down $NAME"
        forever stop $APPLICATION_PATH 2>&1 > /dev/null
        # Get rid of the pidfile, since Forever won't do that.
        rm -f $PIDFILE
        RETVAL=$?
    else
        echo "$NAME is not running."
        RETVAL=0
    fi
}
 
restart() {
    stop
    start
}
 
status() {
#    tst=`sudo service --status-all 2>/dev/null | grep -E 'serv6614' | grep -o '+'` 
    echo start status checking
    tst=`sudo service --status-all | grep -E 'socket_server' | grep -o '+'`
    echo $tst
    if [ "$tst" = "+" ]
    then
        echo "$NAME is running."
        RETVAL=0
    else
        echo "$NAME is not running."
        RETVAL=3
    fi
}
 
case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: {start|stop|status|restart}"
        exit 1
        ;;
esac
exit $RETVAL
